api:  # API type
  cls: OpenAPI  # name of class that is subclass of API
  config: # configuration for defined class
    api_key:  # API key.
    pool_interval: 300 # Interval in seconds for checking the status of the batch request.
    process_request_file_interval: 1 # Interval in seconds between sending requests in process_request_file.
    base_url: # Base URL for API.
